language: node_js
node_js:
  - '8'
  - '6'
cache:
  directories:
    - node_modules
script: 'yarn test:coverage'
after_success: 'yarn test:report'
before_deploy: 'yarn build'
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
